### PR TITLE
Status add reply to

### PR DESCRIPTION
**Pull request by akirk**
To make it easier to reply to ActivityPub messages, you can paste the URL here like so (it'll automatically add the right mentions when it's ready)
reply-to

### CODE REVIEW

**Comment by akirk** [comment]
In coordination with this, I have also released an update to the [Friends Firefox extension](https://addons.mozilla.org/addon/wpfriends/) with Follow support on Mastodon as well as reply support:

Screenshot 2023-04-28 at 16 42 17

**Comment by Zepfanman** [comment]
I know this is closed, but it seems to be related to an issue I'm having. Can you only reply to a subscription post if they also have the Friends plugin?

Reactions and boosts work, but otherwise, it looks like the Reply option on a basic toot doesn't do anything.
image

**Comment by Zepfanman** [comment]
Clicking Reply does nothing. Clicking Comments shows the below:
image

If you look at the toot, you can see that there is another reply. Note: If it looks confusing, I'm using various "zepfanman" Mastodon accounts to test this. https://discuss.systems/@zepfanman/114031257962366030

**Comment by akirk** [comment]
Hm, I just tried it and it worked for me. Do you have access to your server's error log and could check if you find something?

**Comment by akirk** [comment]
Or maybe in the browser's developer tools you could check if the admin-ajax.php request yields an error.

**Comment by Zepfanman** [comment]
Does the attachment help? I'm in Firefox Web Dev, but not sure where I should go to look for an ajax error.
[debug.log](https://github.com/user-attachments/files/19323350/debug.log)

**Comment by Zepfanman** [comment]
There is no comments form. It just does nothing and looks like my initial screenshot above. I'm disabling my plugins one by one, but in the meantime here's the debug error:
MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead. contentscript.js:2:330307
[contentscript.js.txt](https://github.com/user-attachments/files/19325223/contentscript.js.txt)

**Comment by akirk** [comment]
Hm, maybe you have a plugin or the WordPress setting that "closes the comments" for all posts.

**Pull request merged**
